<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/3/26
 * Time: 17:34
 */

namespace common\models\c2\entity;


use common\models\c2\statics\FeUserType;
use cza\base\models\statics\EntityModelStatus;
use yii\helpers\ArrayHelper;

class FamiliarModel extends FeUserModel
{
    public $masterId;
    public $chessId;
    public $degreeId;

    public function loadDefaultValues($skipIfSet = true) {
        parent::loadDefaultValues($skipIfSet);
        $this->type = FeUserType::TYPE_FAMILIAR;
    }

    /**
     * @inheritdoc
     * @return \common\models\c2\query\FeUserQuery the active query used by this AR class.
     */
    public static function find() {
        return parent::find()->familiar();
    }

    public static function getHashMap($keyField, $valField, $condition = '') {
        if (empty($_data['familiarHashMap'])) {
            $lord = FamiliarProfileModel::find()->joinWith(['allFamiliar'])
                ->andWhere(['{{%fe_user}}.type' => FeUserType::TYPE_FAMILIAR]);
            $_data['chieftainHashMap'] = ArrayHelper::map($lord->select([$keyField, $valField])->andWhere($condition)->asArray()->all(), $keyField, $valField);
            return $_data['familiarHashMap'];
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if ($insert) {
            $rs = new MasterFamiliarRsModel();
            $rs->setAttributes([
                'chess_id' => $this->chessId,
                'master_id' => $this->masterId,
                'familiar_id' => $this->id,
            ]);
            $rs->save();
            $rs2 = new UserDegreeRsModel();
            $rs2->setAttributes([
                'user_id' => $this->id,
                'degree_id' => $this->degreeId,
                'type' => $this->type,
            ]);
            $rs2->save();
        }
    }

    public function getPeasants()
    {
        // return $this->hasMany(PeasantModel::className(), ['id' => 'peasant_id'])
        //     ->where(['status' => EntityModelStatus::STATUS_ACTIVE])
        //     ->viaTable('{{%familiar_peasant_rs}}', ['familiar_id' => 'id']);
        return $this->hasMany(FamiliarPeasantRsModel::className(), ['familiar_id' => 'id']);
    }

    public function getCurrentChessUser()
    {
        $currentChess = \Yii::$app->session->get('chess');
        return $this->getPeasants()->where(['chess_id' => $currentChess['chess_id']]);
    }

}