<?php

namespace common\models\c2\entity;

use Yii;

/**
 * This is the model class for table "{{%user_profit_item}}".
 *
 * @property integer $id
 * @property integer $type
 * @property integer $kpi_id
 * @property integer $grp_id
 * @property integer $user_id
 * @property string $income
 * @property integer $state
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
class UserProfitItemModel extends \cza\base\models\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user_profit_item}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kpi_id', 'grp_id', 'user_id'], 'integer'],
            [['income'], 'number'],
            [['created_at', 'updated_at'], 'safe'],
            [['type', 'state', 'status'], 'integer', 'max' => 4],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app.c2', 'ID'),
            'type' => Yii::t('app.c2', 'Type'),
            'kpi_id' => Yii::t('app.c2', 'Kpi ID'),
            'grp_id' => Yii::t('app.c2', 'Grp ID'),
            'user_id' => Yii::t('app.c2', 'User ID'),
            'income' => Yii::t('app.c2', 'Income'),
            'state' => Yii::t('app.c2', 'State'),
            'status' => Yii::t('app.c2', 'Status'),
            'created_at' => Yii::t('app.c2', 'Created At'),
            'updated_at' => Yii::t('app.c2', 'Updated At'),
        ];
    }

    /**
     * @inheritdoc
     * @return \common\models\c2\query\UserProfitItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\c2\query\UserProfitItemQuery(get_called_class());
    }

    /**
     * setup default values
     **/
    public function loadDefaultValues($skipIfSet = true)
    {
        parent::loadDefaultValues($skipIfSet);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if ($insert) {
            $userProfitModel = $this->userProfit;
            if (is_null($userProfitModel)) {
                $userProfitModel = new UserProfitModel();
                $userProfitModel->setAttributes([
                    'user_id' => $this->user_id,
                    'income' => $this->income,
                ]);
                $userProfitModel->save();
            }
            $userProfitModel->updateAttributes(['income' => $this->income]);

        }
    }

    public function getUserProfit()
    {
        return $this->hasOne(UserProfitModel::className(), ['user_id' => 'user_id']);
    }

    public function getUser()
    {
        return $this->hasOne(FeUserModel::className(), ['id' => 'user_id']);
    }

    public function getGRP()
    {
        return $this->hasOne(GRPModel::className(), ['id' => 'grp_id']);
    }

    public function getKpi()
    {
        return $this->hasOne(UserKpiModel::className(), ['id' => 'kpi_id']);
    }

}
