<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Chess' => '盘',
    'Lord' => 'C3',
    'Elder' => 'C2',
    'Chieftain' => 'C1',
    'Master' => 'B层',
    'Familiar' => 'A层',
    'Peasant' => 'P层',
    'User Degree' => '用户等级',
    'User list' => '用户列表',
    'Fe user' => '用户列表',
    'Branch' => '分支',
    '{s1} add' => '{s1}添加',
    'Parent' => '上级用户',
    'Code' => '编码',
    'Username' => '用户名称',
    'Status' => '状态',
    'Active' => '活动',
    'Inactive' => '停止',
    'Kpi' => '考核',
    '' => '',
];

