<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Chess' => '资金盘',
    'Lord' => 'C3',
    'Elder' => 'C2',
    'Chieftain' => 'C1',
    'Master' => 'B层',
    'Familiar' => 'A层',
    'Peasant' => 'P层',
    'User Degree' => '用户等级',
    'User list' => '用户列表',
    'Fe user' => '用户列表',
    'Branch' => '分支',
    '{s1} add' => '{s1}添加',
    'Parent' => '上级用户',
    'Code' => '编码',
    'Username' => '用户名称',
    'Status' => '状态',
    'Active' => '活动',
    'Inactive' => '停止',
    'Kpi' => '考核',
    'New user' => '新用户',
    'Recommend user' => '推荐人',
    'Commit user' => '审核人',
    'Owner user' => '所属上级',
    'Dues' => '转账金额',
    'Kpi commit state' => '审核流程',
    'Not commit' => '待审核',
    'Chieftain commit' => '提交审核',
    'Admin commit' => '管理员审核',
    'Finish commit' => '审核完成',
    'Profit' => '提成金',
    'Award' => '奖励金',
    'Are you sure?' => '确定要执行吗',
    'Not matter kpi commit' => '确认分配数据无误，确认要执行审核通过吗',
    'Operation completed successfully!' => '操作成功!',
    'Update' => '更新',
    'Developments' => '下级成员',
    'Kpi line' => '考核线',
    'User kpi line draw' => '用户考核图',
    'View chess station' => '查看资金盘结构',
    'View degree' => '查看等级',
    '' => '',
    '' => '',
];

