<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // common
    'Menu' => '菜单',
    'Dashboard' => '仪表板',
    'Database' => '资料库',
    '{s1} Management' => '{s1}管理',
    'Product' => '产品',
    'User' => '用户',
    'Measure' => '单位',
    'Currency' => '货币',
    'Logistics' => '后勤资料',
    'System' => '系统',
    'Configuration' => '参数',
    'Common Resource' => '公共资源',
    'Attachement Management' => '附件管理',
    'Global Settings' => '全局配置',
    'Security' => '安全',
    'Users & Rbac' => '角色权限',
    'Sign out' => '退出帐号',
    'Config' => '配置',
    'Logs' => '日志',
    'Region' => '地区',
    'Close' => '关闭',
    'Save' => '保存',
    'Go Back' => '返回',
    'Update' => '更新',
    'Create' => '创建',
    'Cancel' => '取消',
    'Created By' => '创建者',
    'Updated By' => '更新者',
    'Are you sure?' => '你确定执行改动作吗',
    'Init' => '初始化',
    'Finish' => '完成',
    'View' => '查看',
    'Edit' => '修改',
    'Created At' => '创建时间',
    'Updated At' => '更新时间',
    'Label' => '标签',
    'Type' => '类型',
    'Default' => '默认',
    'Province' => '省份',
    'City' => '城市',
    'District' => '区/镇',
    'Last Login Ip' => '最后登录IP',
    'Mobile Number' => '手机号码',
    'Registration Src Type' => '注册来源',
    'Select Options ...' => '请选择...',
    'Last Login At' => '最后登录时间',
    'Registration Ip' => '最后登录IP',
    'Add' => '添加',
    'Delete' => '删除',
    // other
    'GRP' => 'GRP',
    'User Degree' => '用户等级',
    'User list' => '用户列表',
    'Branch' => '分支',
    '{s1} add' => '{s1}添加',
    'Parent' => '上级用户',
    'Code' => '编码',
    'Username' => '用户名称',
    'Status' => '状态',
    'Active' => '活动',
    'Inactive' => '停止',
    'Kpi' => '考核',
    'New user' => '新用户',
    'Fe User Models' => '用户列表',
    'Fe User Model' => '用户',
    'G R P Models' => 'GRP列表',
    'G R P Model' => 'GRP',
    'GRP Chart' => 'GRP图表',
    'GRP Station' => 'GRP岗位',
    'Selected Node' => '被选中的节点',
    'New Node' => '新节点名称',
    'Children Node' => '下级节点',
    'Sibling Node' => '同级节点',
    'Reset Node' => '清除选择',
    'GRP Chart Member' => 'GRP岗位成员',
    'Node Nav' => '节点方向',
    'Join User' => '新会员',
    'Invite User' => '邀请会员',
    'Grp Station' => '岗位',
    'Dues' => '转帐金额',
    'Commit' => '审核',
    'Name' => '名称',
    'Selected Id' => '被选中的节点',
    'Station has items.' => '改岗位有人员，请先删除人员。',
    'Invite User ID' => '推荐人',
    'Invite Username' => '邀请人',
    '' => '',
];

