<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/15
 * Time: 10:42
 */

namespace backend\models\c2\entity;


use common\models\c2\entity\UserChessRsModel;
use common\models\c2\entity\UserDegreeRsModel;
use yii\helpers\ArrayHelper;

class FeUserModel extends \common\models\c2\entity\FeUserModel
{
    public $chess_id;
    public $degree_id;

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['chess_id', 'degree_id'], 'required'],
        ]);
    }

    public function loadDefaultValues($skipIfSet = true)
    {
        parent::loadDefaultValues($skipIfSet); // TODO: Change the autogenerated stub
        $model = $this->userDegree;
        if ($model != null) {
            $this->degree_id = $model->id;
            $this->chess_id = $model->chess->id;
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if ($insert) {
            $model = new UserDegreeRsModel();
            $model->setAttributes([
                'degree_id' => $this->degree_id,
                'user_id' => $this->id,
                'type' => $this->type,
            ]);
            $model->save();
            $model2 = new UserChessRsModel();
            $model2->setAttributes([
                'user_id' => $this->id,
                'chess_id' => $this->chess_id,
            ]);
            $model2->save();
        } else {
            if (isset($changedAttributes['degree_id'])) {
                $model = $this->userDegree;
                $model->updateAttributes([
                    'degree_id' => $this->degree_id
                ]);
            }
            if (isset($changedAttributes['chess_id'])) {
                $model2 = $this->chess;
                $model2->updateAttributes([
                    'chess_id' => $this->chess_id
                ]);
            }
        }
    }

}