<?php
/**
 * Created by PhpStorm.
 * User: jerrygo
 * Date: 19-5-28
 * Time: 下午4:13
 */

namespace backend\models\c2\entity;


use common\models\c2\entity\GRPStationModel as BaseModel;
use yii\helpers\ArrayHelper;

class GRPStationModel extends BaseModel
{
    public $node_nav;
    public $selected_id;

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['grp_id', 'label', 'node_nav', 'selected_id'], 'required'],
        ]); // TODO: Change the autogenerated stub
    }

}