<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/30
 * Time: 17:14
 */

namespace frontend\controllers;


use frontend\components\Controller;
use yii\helpers\ArrayHelper;

class BaseController extends Controller
{

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'userTypeFilter' => [
                'class' => UserTypeBehavior::className(),
                'chessUserType' => FeUserType::TYPE_MASTER
            ],
        ]); // TODO: Change the autogenerated stub
    }

}