<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Application' => '原玉平台',
    'Base Information' => '基本信息',
    'Multiple Language' => '多语言录入',
    'Search' => '搜索',
    'Settings' => '设置',
    'Not set' => '未设置',
    'Sms Verify Code Sent!' => '验证码已发出！',
    'Retrive Sms Code' => '获取验证码',
    'Cannot send sms verify code!' => '短信发送故障！',
    'seconds resend' => '秒后重发',
    '{attribute} must be mobile format!' => '{attribute} 必须是11位长度1开头的标准手机号码',
    'Username is already existed!' => '该用户名已经被占用!',
    'Mobile number is already existed!' => '该手机号已经被占用!',
    'Welcome to signup' => '欢迎您的加入',
    'Mobile Number' => '手机号码',
    'Signup' => '注册',
    'Recommend Code' => '推荐码',
    'Login' => '登录',
    'Signup Account' => '注册帐号',
    'Base Profile' => '基本信息',
    'User degree' => '用户等级',
    'Register At' => '注册时间',
    'Recommend code has been expired after 15min' => '推荐码有效时间15分钟',
    'Generate' => '生成推荐码',
    'The Recommend code is incorrect.' => '推荐码过期或不正确',
    'My members' => '我的成员',
    'Back' => '返回',
    'This username has already been taken.' => '该用户名已被注册',
    'This mobile number has already been taken.' => '该手机号已被注册',
    'Login Account' => '马上登陆',
    'Lord' => 'C3层',
    'Elder' => 'C2层',
    'Chieftain' => 'C1层',
    'Master' => 'B层',
    'Familiar' => 'A层',
    'Peasant' => 'P层',
    'User Register' => '用户注册',
    'Profile center' => '个人中心',
    'Login account right now' => '已有帐号?马上登录',
    'Username' => '用户名称',
    'Password' => '登录密码',
    'Sms code' => '验证码',
    'Developments' => '发展成员',
    'Chess not in' => '尚没有加入资金盘',
    'Tips' => '提示',
    'Chess user type has been change.' => '用户等级发生改变，请您重新登陆',
    'Data empty' => '暂无数据',
    'Current chess' => '当前资金盘',
    'Change' => '更换',
    '{attribute} "{value}" has already been taken.' => '已被占用',
    'Created at' => '建立时间',
    'Register at' => '注册时间',
    'Setting' => '设置',
    'Kpi list' => '考核列表',
    'Commit' => '审核',
    'Not commit' => '待审核',
    'Recommend user' => '推荐人',
    'Detail' => '查看',
    '' => '',
];
