<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'REST: Success' => '接口调用成功',
    'REST: ERROR_INTERNAL' => '服务器内部错误',
    'REST: ERROR_300' => '缺少key参数',
    'REST: ERROR_400' => '域名错误',
    'REST: ERROR_401' => '未经合法授权,请求无效！',
    'REST: ERROR_402' => '该域名已禁用',
    'REST: ERROR_403' => '禁止访问',
    'REST: ERROR_404' => '资源不存在',
    'REST: ERROR_405' => '错误的请求类型',
    'REST: ERROR_501' => '数据库错误',
    'REST: ERROR_502' => '并发异常，请重试',
    'REST: ERROR_600' => '缺少参数',
    'REST: ERROR_601' => '无权操作:缺少 token',
    'REST: ERROR_602' => '签名错误',
    'REST: ERROR_700' => '暂无数据',
    'REST: ERROR_701' => '该功能暂未开通',
    'REST: ERROR_702' => '资源余额不足',
    'REST: ERROR_901' => 'token错误',
    'REST: ERROR_902' => '第三方接口调用发生错误',
    'Your request was made with invalid credentials.' => "未经合法授权,请求无效！",
    'Access Token is expired!' => 'Access Token已过期！',
    'Incorrect Signature!' => '无效签名！',
    'Error: Signature authenticated failed!' => '错误：签名认证失败！',
    'Signature authenticated successfully!' => '签名认证成功！',
    'Resource not found!' => '资源不存在!',
    'Failed to delete the object for unknown reason.' => '删除失败！',
    'Incorrect Signature!' => '签名验证失败！',
    'Incorrect Order!' => '无效订单！',
    'Fail to inovke 3rd API!' => '调用第三方接口失败！',
    '{s1} Unavailable!' => '{s1}状态不可用！',
];
