<?php

namespace frontend\modules\Persant\controllers;

use common\models\c2\entity\UserChessRsModel;
use common\models\c2\statics\FeUserType;
use cza\base\models\statics\EntityModelStatus;
use frontend\components\behaviors\UserTypeBehavior;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

/**
 * Default controller for the `peasant` module
 */
class DefaultController extends Controller
{

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
           'userTypeFilter' => [
               'class' => UserTypeBehavior::className(),
               'chessUserType' => FeUserType::TYPE_PEASANT
           ],
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $familiarModels = UserChessRsModel::find()->where(['chess_id' => 3, 'type' => FeUserType::TYPE_FAMILIAR])
            ->andFilterWhere(['status' => EntityModelStatus::STATUS_ACTIVE])
            ->orderBy(['position' => SORT_ASC])
            ->asArray()
            ->all();
        return $this->render('index');
    }
}
