<?php
/**
 * Created by PhpStorm.
 * User: jerrygo
 * Date: 19-5-22
 * Time: 下午11:47
 */

namespace frontend\models;


use common\components\SmsCaptcha\CaptchaValidator;
use common\models\c2\entity\FeUserModel;
use cza\base\models\ModelTrait;
use Yii;
use yii\base\Model;

class ForgetPasswordForm extends Model
{
    use ModelTrait;

    public $mobile_number;
    public $password;
    public $passwordTwice;
    public $verifyCode;

    public function rules()
    {
        return [
            ['mobile_number', 'required'],
            [['mobile_number',], 'match', 'pattern' => '/^1[0-9]{10}$/', 'message' => Yii::t('app.c2', '{attribute} must be mobile format!')],
            [['mobile_number'], 'string', 'length' => 11],
            [['mobile_number'], 'number', 'integerOnly' => true],
            [['password', 'passwordTwice',], 'string', 'min' => 6],
            ['passwordTwice', 'compare', 'compareAttribute' => 'password'],
            ['verifyCode', CaptchaValidator::className()],
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'mobile_number' => Yii::t('app.c2', 'Mobile Number'),
            'password'=> Yii::t('app.c2', 'Password'),
            'passwordTwice'=> Yii::t('app.c2', 'Password Twice'),
            'verifyCode' => Yii::t('app.c2', 'Verification Code'),
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        $user = FeUserModel::findByMobileNumber($this->mobile_number);
        $user->setPassword($this->password);
        $user->generateAuthKey();
        return $user->save() ? $user : null;
    }

}