<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/12 0012
 * Time: 下午 14:25
 */

namespace frontend\models;


use common\models\c2\entity\UserSumApplyModel;
use Yii;
use yii\helpers\ArrayHelper;

class SumApplyForm extends UserSumApplyModel
{

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['apply_sum',], 'validateSum'],
            [['apply_sum', 'bank_name', 'name', 'mobile_number', 'bank_card_number'], 'required'],
        ]);
    }

    public function validateSum($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = Yii::$app->user->currentUser;
            $profitModel = $user->profit;
            if ($this->apply_sum > $profitModel->income) {
                $this->addError($attribute, Yii::t('app.c2',
                    'Sum apply can more {s1}.', ['s1' => $profitModel->income]));
            }
        }
    }

    // public function afterSave($insert, $changedAttributes)
    // {
    //     parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    //     if ($insert) {
    //         $user = $this->user;
    //         $user->profit->updateCounter(['imcome' => -($this->apply_sum)]);
    //     }
    // }

}