<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/15
 * Time: 10:09
 */

namespace frontend\widgets;


use yii\base\Widget;

class ChessSelector extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $user = \Yii::$app->user->currentUser;
        $chess = $user->chess;
        $currentChess = \Yii::$app->session->get('chess');
        if (is_null($currentChess)) {
            if ($chess != null) {
                \Yii::$app->session->set('chess', ['chess_id' => $chess[0]->id, 'chess_name' => $chess[0]->label]);
            }
        }
        return $this->render('chess_selector', [
            'model' => $chess
        ]);
    }
}