<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/15
 * Time: 10:09
 */

namespace frontend\widgets;


use yii\base\Widget;
use yii\helpers\ArrayHelper;

class ChessSelector extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $user = \Yii::$app->user->currentUser;
        $model = $user->getChess()->all();
        return $this->render('chess_', [
            // 'model' => ArrayHelper::remove($model, $current_chess_id),
            'model' => $model,
        ]);
    }
}