<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/9
 * Time: 15:34
 */

namespace frontend\widgets;


use yii\base\Widget;

class MemberListWidget extends Widget
{

    public $dataProvider;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('member_list', ['dataProvider' => $this->dataProvider]);
    }

}