<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/7
 * Time: 12:22
 */

namespace frontend\widgets;


use common\models\c2\entity\FeUserModel;
use yii\base\Widget;

class ProfilePanel extends Widget
{
    /**
     * @var FeUserModel
     */
    public $user;

    public $isChieftain = false;
    public $isShowDevelopment = false;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $stations = $this->user->getUserChessRs()->all();
        return $this->render('profile_panel', [
            'user' => $this->user,
            'stations' => $stations,
            'isChieftain' => $this->isChieftain,
            'isShowDevelopment' => $this->isShowDevelopment,
        ]);
    }
}