<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/8
 * Time: 22:22
 */

namespace frontend\widgets;


class RCodeGenerator extends \kartik\base\Widget
{
    public $captchaAction = '/site/recommend-code-captcha';

    /**
     * @var array HTML attributes to be applied to the CAPTCHA image tag.
     * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
     */
    public $buttonOptions = ['class' => 'btn btn-info w100'];

    /**
     * @var array the HTML attributes for the input tag.
     * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
     */
    public $options = ['class' => 'card'];

    /**
     * @var string the template for arranging the CAPTCHA image tag and the text input tag.
     * In this template, the token `{image}` will be replaced with the actual image tag,
     * while `{input}` will be replaced with the text input tag.
     */
    public $template = '';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        // $this->registerClientScript();
        return $this->render('RCode', [
            'captchaAction' => $this->captchaAction
        ]);
    }

    public function registerClientScript()
    {
        $view = $this->getView();
        // $chess_id = \Yii::$app->session->get('chess_id');
        // if (!is_null()) {
        //
        // }
        $js = "$('#gen').click(function generate() {
                    $.post('{$this->captchaAction}', function(data) {
                      if (data) {
                          $('#recommend-broad').html(data.data)
                      } 
                    });
                });";
        $view->registerJs($js);
    }


}