<?php

namespace frontend\modules\Familiar\controllers;

use common\models\c2\entity\FamiliarModel;
use common\models\c2\search\PeasantSearch;
use common\models\c2\statics\FeUserType;
use frontend\components\behaviors\UserTypeBehavior;
use frontend\widgets\MemberListWidget;
use Yii;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

/**
 * Default controller for the `familiar` module
 */
class DefaultController extends \frontend\components\Controller
{
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'userTypeFilter' => [
                'class' => UserTypeBehavior::className(),
                'chessUserType' => FeUserType::TYPE_FAMILIAR
            ],
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {

        return $this->render('index', [
        ]);
    }


}
