<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/29
 * Time: 13:58
 */

namespace backend\models\c2\form;


use common\models\c2\entity\UserChessRsModel;
use common\models\c2\entity\UserDevelopmentModel;
use cza\base\models\ModelTrait;
use yii\base\Model;

class DevelopmentForm extends UserChessRsModel
{

    // public $chess_id;
    // public $user_id;
    // public $type;
    //
    // use ModelTrait;

    public $parent_id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->loadDefaultValues();
    }


    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if ($insert) {
            $attrs = [
              'user_chess_rs_id' => $this->parent_id,
              'chess_id' => $this->chess_id,
              'user_id' => $this->user_id,
              // 'parent_id' => $this->parent_id,
              'type' => $this->type,
              'position' => $this->position,
            ];
            $model = new UserDevelopmentModel();
            $model->setAttributes($attrs);
            $model->save();
        }
    }
}