<?php

namespace frontend\modules\Master\controllers;

use common\models\c2\statics\FeUserType;
use frontend\components\behaviors\UserTypeBehavior;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

/**
 * Default controller for the `master` module
 */
class DefaultController extends Controller
{

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'userTypeFilter' => [
                'class' => UserTypeBehavior::className(),
                'chessUserType' => FeUserType::TYPE_MASTER
            ],
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        // $user = $user = Yii::$app->user->currentUser;
        // Yii::info($user->currentChess);
        return $this->render('index', [
        ]);
    }

}
